# Professional-grade dependency compliance configuration

[advisories]
# Fail on any security advisory
vulnerability = "deny"
unmaintained = "warn"
unsound = "warn"
notice = "warn"

[licenses]
# Strictly control allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "MIT OR Apache-2.0",  # Very common dual license
]
confidence-threshold = 0.8

[bans]
# Allow multiple versions temporarily for Windows crates (common issue)
multiple-versions = "warn"
wildcards = "deny"

# Allow known problematic Windows crates that have version conflicts
skip = [
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "windows-link",
]

[sources]
# Only allow crates.io
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]