# Versioneer project hooks - using shared Rust quality library
# Imports comprehensive hooks from shared library

imports = ["/Users/jfb/.local/peter-hook/shared.toml"]

# =============================================================================
# PROJECT-SPECIFIC HOOK GROUPS
# =============================================================================

[groups.pre-commit]
includes = ["comprehensive-pre-commit"]
execution = "sequential"
description = "Complete pre-commit quality assurance using shared hooks"

[groups.commit-msg]
includes = ["commit-validation"]
execution = "sequential"
description = "Commit message validation using shared hooks"

# Pre-push hooks - additional expensive checks (commented out until tools installed)
# [hooks.semver-check]
# command = "cargo semver-checks"
# modifies_repository = false
# description = "Check for SemVer compliance"

# [hooks.unsafe-analysis]
# command = "cargo geiger"
# modifies_repository = false
# description = "Analyze unsafe code usage"

# [groups.pre-push]
# includes = ["semver-check", "unsafe-analysis"]
# execution = "parallel"
# description = "Pre-push checks: comprehensive testing and validation"